### PR TITLE
Create our own runtime more something more rusty.

### LINKED ISSUE #10: Type of Callback
The `rdev::Callback` type is a function pointer (`fn`) and not a `std::ops::Fn` (`Fn`), so it is not possible to use closures. Changing to `Fn` would probably break backwards compatibility, but it would be relatively easy for users to fix. In the following example I want to send the mouse positions over a chanel (which is not `Sync`, so I can't share the whole thing between threads, just give out the ends individually).

```rust
use rdev::{listen, Event, EventType};
use std::sync::mpsc::{channel, Sender, Receiver};

fn callback(event: Event, sender: Sender<(f64, f64)>) {
    match event.event_type {
        EventType::MouseMove{x, y} => {
            sender.send((x,y));
        }
        _ => {}
    }
}

fn main() {
    let (send, recv) = channel();
    // bind callback's send to local variable send
    let bound_callback = |x| callback(x, send);
    listen(bound_callback); // <- error here, bound_callback is `Fn`, not `fn`
    // spawn a new thread to receive
}

```
Changing the type of Callback would be awesome, but it might make more sense for you to use `futures::stream::Stream` (basically a series of `Futures`) instead of callbacks for the next major release. This would majorly break backwards compatibility in a way that is hard for users to fix. The rust ecosystem is heavily investing in futures, so it seems like a good choice.

### PR DESCRIPTION
**Pull request by Narsil**
Fixes #10

### CODE REVIEW

**Comment by maxbla** [comment]
I'm not entirely sure what the [differences](https://book.async.rs/overview/std-and-library-futures.html) are between async-std and futures-rs, but futures is a bit older and async-std depends on futures-core. I feel like `futures` would be a better dependency, as it's `channel` is not marked unstable. (there was actually some discussion of stabilizing streams recently, and a PR did that, but then the PR was reverted https://github.com/async-rs/async-std/issues/711)

Also regarding the title of this PR, currently "Create our own runtime...". This PR actually never uses or creates an `Executor` (runtime), as `block_on()` turns the asynchronous code synchronous. In this code, you return a Stream to the user, so they have the option of using a runtime, or not - they could also `block_on()`.

**Comment by Narsil** [comment]
> I'm not entirely sure what the differences are between async-std and futures-rs, but futures is a bit older and async-std depends on futures-core. I feel like futures would be a better dependency, as it's channel is not marked unstable. (there was actually some discussion of stabilizing streams recently, and a PR did that, but then the PR was reverted async-rs/async-std#711)

Between async-std, tokio, future-rs, std::futures I must admit I'm a bit lost. What are the tradeoffs between them ? So far my understanding is that it's maturity + intended stability.

>Also regarding the title of this PR, currently "Create our own runtime...". This PR actually never uses or creates an Executor (runtime), as block_on() turns the asynchronous code synchronous. In this code, you return a Stream to the user, so they have the option of using a runtime, or not - they could also block_on().

Isn't task::spawn moving the code into some event loop ? It might have been a tokio conf I watched but I thought some runtime were global and running for you, so as a user `spawn` was enough to create the runtime. Am I mistaken ?

**Comment by maxbla** [comment]
> Isn't task::spawn moving the code into some event loop

You're close, but no, I think not. `Task::spawn` creates a `JoinHandle`, which is a `Future`. Futures in Rust are lazy - they do nothing until you call poll on them (all executors do this under the hood). Since you `block_on` the future, basically calling poll in a busy loop, there is never an event loop. Also idk if you tested the code you wrote, but it looks to me like that task will never return, since listen() only returns on error. Furthermore async-std doesn't contain an executor, so you'd need another dependency to get an event loop.

> I must admit I'm a bit lost

Rust's async situation is complicated... But it will get better soon. Let me try to summarize. std::future::Future is just a Trait, an interface - it says what it means to be a future. This interface was copy pasted from the futures-rs crate, so it could be an official standard. futures-rs provides futures-related traits (Stream, Executor) used by all the other crates and it implements some async primitives - channels, multiple executors and futures-aware mutexes (required to prevent unavoidable deadlock). Async-std is exactly what it says it is - a rewrite of the standard library, where all I/O is async i.e. returns futures. The sync standard library includes synchronous versions of async primitives (like channels), so there is some overlap with futures-rs. Tokio is mainly known for its high-performance work stealing executor (aka event loop/runtime), which is heavily used in networking. Tokio also re implements lots of futures-rs (but not the async traits), gated behind the sync feature.  There's one more crate to be aware of in the async landscape - mio. Mio is a cross-platform interface to kernel-level event callbacks (kqueues, epoll, IOCP, etc.). Tokio is based on mio and that's what makes it so fast. Async-std also uses mio, but futures-rs doesn't - that's because it doesn't have any file or network I/O.

**Comment by Narsil** [comment]
I did test,  and it seems to work. But all what you are saying are letting me to believe that I probably don't want to include any async in this library. Users will have to use whatever they prefer, I don't think making a choice for them is wise. The purpose here is to focus on providing a single API to target System wide events for all 3 major OSes. I would rather work to add more features like grabbing events that working on having the best async framework working.

**Comment by maxbla** [comment]
I think it is early to include async in this library. Waiting at least until the Futures crate releases a 1.0 version will reduce churn. I was trying to communicate the immaturity of `async` in Rust when I said

> it might make more sense for you to use futures::stream::Stream (basically a series of Futures) instead of callbacks **for the next major release**

I think there are two good ways to fix #10 and one of them involves async. I'll post my current thoughts in that issue.

**Comment by Narsil** [comment]
I'm closing this. It doesn't seem right to choose an async implementation in this library for the moment.

**Pull request closed without merging**
