### PR TITLE
Update documentation for unstable_grab feature

### PR DESCRIPTION
**Pull request by alextremblay**
Update documentation as per https://github.com/Narsil/rdev/issues/42#issuecomment-852997081

### CODE REVIEW

**Review by Narsil — CHANGES_REQUESTED** [review]
Could we just keep this modification to adding the example for `unstable_grab` ?

Your example seems broken too as you are not returning the event if it's not a CapsLock key event. (You can run `cargo test --all-features --all-targets` && `cargo clippy --all-features --all-targets` to check your PR)

Also could you revert all the text modifications to their previous versions: 
- `global input device event stream` for instance is incorrect both for Windows and MacOS (someone could always be higher up in the chain than you for instance). (And it's not the README's place to dive into OS specific considerations).
- Also `OS specificities` need to be higher than the `unstable_` feature, because well unstable is unstable so it's by definition less important than the rest.
- also the `listen` on linux does not use `evdev` but real X11 mechanism (so no special permissions needed).
 
Caveats` is probably better than `Specificities` though.

**Comment by alextremblay** [comment]
Thanks @Narsil,

Following your suggestion, I cleaned up the documentation and split the "OS Caveats" section into a separate section for each of the `listen` and `grab` functions, making them more prominent and explicit

I've run the cargo tests and clippy checks you suggested on windows and MacOS, and all the tests pass.

Could you please review?

**Review by Narsil — APPROVED** [review]
Thanks, LGTM.

**Comment by Narsil** [comment]
In order to pass quality, you should change the `lib.rs` file first, then run  `cargo readme > README.md`.

**Comment by alextremblay** [comment]
not sure how I managed to lose that semicolon, but it's been re-added, and `cargo test`, `cargo clippy`, and `cargo fmt` have all been successfully run

**Comment by alextremblay** [comment]
oh that's an interesting error...

i see in the github ctions workflow file that only the serialize feature is enabled, and there's a note saying that `grab` is not supported in linux. is this a holdover from before the evdev refactoring, or is `grab` testing on linux disabled for some other reason?

I just booted up my linux laptop, cloned the repo to it, and ran the doctests with all features enabled, and it passed all tests.

should i add a `//! #[cfg(feature = "unstable_grab")]` line to each section of the grab example, or should i modify the rust.yaml file to enable unstable_grab in linux?

**Review by Narsil — APPROVED** [review]

**Pull request merged**
